### Registrar usuario
POST http://localhost:3000/api/registrar
Content-Type: application/json

{
  "nombre": "mariel velizs",
  "correo": "mariel.vels@usm.cl",
  "clave": "asd",
  "descripcion": "kaksada"
}

### Bloquear usuario
POST http://localhost:3000/api/bloquear
Content-Type: application/json

{
  "correo": "daniel.duenas@usm.cl",
  "clave": "clavecita1234",
  "correo_bloquear": "mariel.vel@usm.cl"
}

### Obtener información pública de un usuario
GET http://localhost:3000/api/informacion/mariel.vels@usm.cl
Content-Type: application/json